theme: jekyll-theme-cayman
title: 阿轩成长情报雷达
description: 聚焦成长、认知、内容创作与 AI 工具的每日中文简报
baseurl: "/Horizon" # the subpath of your site, e.g. /blog
url: "https://shanexxzz.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
future: true # Allow future posts to be published
plugins:
  - jekyll-feed
feed:
  path: feed.xml
exclude:
  - ".github"
  - "node_modules"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
